<?php require_once "../../php/init.php"; ?><html><head><meta charset="utf-8"><title>Grasslands, meadows and farms - Brecon Beacons National Park, Wales</title><script type='text/javascript' src='../../js/main.min.js'></script></head><body><div class="main-content clearfix">
<!--SearchStart//-->
<h1>Grasslands, meadows and farms</h1>
<div class="article-video right clearfix"/>
<p/><p>
<span style="font-size:18px;">The lower slopes of the uplands and the river valleys in the Brecon Beacons National Park have been farmed for thousands of years. As humans have worked the land it has created a rich collection of grasslands, meadows, hedgerows and orchards.</span></p>
<p>
<img src="/website/var/tmp/thumb_1129__auto_39b0de0fb9c13d9d5c4a8ab240b964e9.jpeg" style="width: 704px; height: 478px; margin-top: 15px; margin-bottom: 15px; float: right;"/>The variety of rocks that form the landscape of our National Park influence the soil that develops above. These soils have a different acidicity or ability to hold water and so encourage vegetation suited to those conditions. A variety of different grasslands have developed on these different soils.</p>
<p>Farming has also created some artificial habitats that have now exisited for so long we will often think of them as natural. Hedgerows are lines of cut and pruned trees created simply as a means of containing stock, while the selective planting of fruit trees created orchards.</p>
<h2>Hedgerows</h2>
<p>There are around 3500 miles of hedgerows in our National Park. While hedgerows are a man-made habitat, the network they form is a valuable substitute for the vast woodland areas and glades that existed before trees were felled to provide fields for farming.</p>
<p>Hedgerows were used to retain stock in pasture and to mark out land ownership boundaries. In doing so a new habitat was created, one that mimicked some of the functions of native woodlands. Trees native to the region were planted or retained to form these long lines. Periodic cutting or laying created a dense growth that prevented stock roaming free while providing shelter from wind and rain. Often hedges were built on banks or alongside drainage ditches, creating further new habitats.</p>
<p>These hedge trees provide flowers, fruit and nest sites for many woodland mammals and birds in otherwise open and inhospitable habitats. The cover they provide allows birds, bats and mammals to cross these open areas and they are essential to link areas used for nesting and foraging.</p>
<p>At the base of the hedge, cover is provided for woodland plants, while the open grasslands around have also brought in other species that thrive under the protection of the hedge.</p>
<h2>Arable field margins</h2>
<p>Modern arable fields contain a single crop with very little to offer wildlife, but it wasn't always this way. Before fertilisers and herbicides created these intensive fields, crops grew in amongst any number of grasses and wildflowers blown into the field. A number of species grew together, attracting birds, insects and small mammals to feast on the seed, fruit and flowers available.</p>
<p>While most of our modern agricultural systems exclude weeds to boost productivity, there is opportunity along the field boundaries to create these wildlife rich areas. Where seeds will always blow in, or the field edges are less productive, some farmers leave field margins to shoot with wildflowers. These areas are particularly important for several bird species for the cover and food they provide. The tall herbs and other flowers are an important refuge for small mammals, particularly when the field is harvested.</p>
<p>These wild edges can have benefits to the farm as well. These areas encourage insects like ladybirds, who have an appetite for some crop pests.</p>
<h2>Floodplain grazing marsh</h2>
<p>The periodic flooding of rivers deposits nutrients along the river margins. River valleys contain some of our most productive and valuable farmland.</p>
<p>Where these areas have been grazed a rich grassland habitat has been created. The grazed fields are almost always separated by ditches to help drainage and they are often rich in plants and invertebrates. Almost all areas are grazed though some are cut for hay or silage. Some grasslands may contain seasonal water-filled hollows and permanent ponds. They are often close to areas of fen or reedswamp.</p>
<p>Areas of shallow puddles in the wetter months are home to large numbers of small invertebrates in the soil and they are an important feeding area for a number of wetland birds such as lapwings and teals.</p>
<h2>Calcareous grasslands</h2>
<p>Grasslands on limestone within the National Park have developed vegetation adapted to the calcium-rich, free-draining soil. These are called calcareous (calcium-loving) grasslands and include areas in both the lowlands and uplands. It is one of the most scarce types of grassland in the National Park.</p>
<p>Calcarerous grasslands are only found where the limestone outcrops as a thin band across the National Park and isolated outcrops elsewhere. They are typically managed as tightly grazed pasture supporting sheep, cattle or sometimes horses. Calcareous grassland sites occur in both enclosed and unenclosed situations and within the National Park are also found immediately around areas of limestone pavement. The cover of lowland calcareous grassland has suffered a sharp decline in extent over the last 50 years, particularly as lowland areas have been modified by agriculture to be more productive. This has enabled more animals to graze, but also excluded many species of wildflower.</p>
<p>Lowland calcareous grasslands support a very rich flora including many nationally rare and scarce species while it also supports birds and butterflies like the common blue. Hawthorn, blackthorn or gorse scrub is often found on or around calcareous grasslands and this can encourage more wildlife by providing shelter for invertebrates, reptiles and birds.</p>
<h2>Lowland acid grasslands</h2>
<p>Specific communities of grasses and flowers grow in acidic areas where the soils are usually free draining, high in sands and gravels and low in nutrients. This creates a dry, acidic grassland.</p>
<p>The lack of water and nutrients has encouraged the development of a community of species that can cope with these conditions. During summer the ground may become parched, reducing the cover of grass and producing areas of bare ground. These bare patches can be very important for a number of insects as they heat up quickly in the sun. Bare areas also allow simple plants like lichens the opportunity to grow amongst grasses that would otherwise smother them.</p>
<p>In the lowlands this habitat is now scarce as it has disappeared due to agricultural improvement. Acidic grasslands occur across the uplands but are often wetter and are degraded examples of habitats such as blanket bog and upland heath.</p>
<p>Lowland acid grasslands often occur along with lowland heath forming a mosaic of grass and heath area. It is normally managed as pasture.</p>
<h2>Meadows</h2>
<p>Soils that are neither acidic or alkaline (neutral) support a variety of wildflowers and grasses. These meadows are rich in wildlife and were created by traditional farming practices. In the past, hay meadows were an important part of the farm as they grew a grass crop that could be dried and stored for use during winter. The cycle of cutting and removing each year's grass created a stunning mix of wildflowers.</p>
<p>This meadow flora can occur on many areas of neutral grassland including most areas of unimproved neutral grassland across the lowlands. It is not restricted to grasslands cut for hay, but also includes unimproved neutral pastures where livestock grazing is the main land use. On many farms, use of particular fields for grazing pasture and hay cropping change over time but the plant communities persist with only slight changes depending on which plants are favoured by the current management.Â </p>
<p>In non-agricultural settings, such grasslands are less frequent but additional examples may be found in recreational sites, church-yards, roadside verges and a variety of other localities.</p>
<p>The recent move to cut silage rather than hay and to add fertiliser to pasture has led to a loss of this meadow flora across the landscape. Silage makes an energy rich feed for livestock but the early cutting prevents many wildflowers from seeding properly, which has a knock-on effect for insects, birds and mammals.</p>
<p>Meadows may remain on small holdings as they were often located near to farm buildings, making it easier to bring in and store the hay crop.</p>
<h2>Rhos pastures</h2>
<p>Rhos is the Welsh name for this particular type of grassland, which occurs on poorly drained soil and is dominated by purple moor grass and rushes. They occur across western Europe, most frequently in areas of high rainfall. South Wales has some of the best examples in Europe of this scarce habitat.</p>
<p>The long, tough grasses provide cover and shelter, making rhos pastures a favoured habitat for birds like snipe and curlew. The marsh fritillary is a butterfly particularly associated with this habitat, as it contains both its food plant, devil's bit scabious, and the thick tussocks that shelter the caterpillars over winter.</p>
<p>The rhos pasture within the National Park has some key populations of marsh fritillaries that are among the best anywhere in the world. It is essential that this habitat is maintained with low intensity grazing by cattle and horses. Sheep find the tough grasses of this habitat unpalatable and many areas have been lost by encouraging other grasses to take over so that sheep can be farmed.</p>
<h2>Traditionally managed orchards</h2>
<p>Small orchards of mixed fruit trees were a part of almost every farm or small holding a century ago. Orchards of mixed trees usually with grazed pasture beneath them have been replaced over the years with other farm crops or rows of small, high yield trees. These traditional style orchards exist now only as small patches within the farmed landscape.</p>
<p>While only small and scattered orchards exist in the National Park, they can be important areas for wildlife. Often the trees are old and are covered in mosses and lichens some of which are now scarce as they live only on old trees.</p>
<p>The large number of flowers available when the trees are in blossom can be an important food source for bees and other insects. Often where orchards remain, the land around is also of high value to wildlife as it may have existed like this for many years.</p>
<p>Old hedges and trees that surround the orchard have not been removed and the grassland beneath the trees has never been ploughed or fertilised, meaning that many wildflowers and fungi may live amongst the fruit trees.</p>

<!--SearchEnd//-->
<div class="hightlights"/></div></body></html>