<?php require_once "../../php/init.php"; ?><html><head><meta charset="utf-8"><title>46. Abergavenny Tourist Information and National Park Centre - Brecon Beacons National Park, Wales</title><script type='text/javascript' src='../../js/main.min.js'></script></head><body><div class="main-content clearfix">
<!--SearchStart//-->
<h1>46. Abergavenny Tourist Information and National Park Centre</h1>
<div class="article-video right clearfix"/>
<p/><p class="documentDescription" style="margin: 0em 0em 0.5em; line-height: 1.5em; font-weight: bold; color: rgb(85, 85, 85); font-family: 'Lucida Grande', Verdana, Lucida, 'Lucida sans', Helvetica, Arial, sans-serif; font-size: 13px; text-align: right;">
<span style="font-size:14px;"><span style="font-family:trebuchet ms,helvetica,sans-serif;"><span><span style="color:#008000;"><img src="/website/var/tmp/thumb_710__auto_850904660de984af948beee3aee98a4f.jpeg" style="width:600px;"/></span></span></span></span></p>
<p class="documentDescription" style="margin: 0em 0em 0.5em; line-height: 1.5em; font-weight: bold; color: rgb(85, 85, 85); font-family: 'Lucida Grande', Verdana, Lucida, 'Lucida sans', Helvetica, Arial, sans-serif; font-size: 13px;">
<span style="font-size:14px;"><span style="font-family:trebuchet ms,helvetica,sans-serif;"><span id="parent-fieldname-description"><span style="color:#008000;">Brecon Beacons Tourist Information and National Park Centre with displays, books, gifts and maps.
<br/>
<br/>Further information</span></span></span></span></p>
<p style="margin: 3px 0px 7px; padding: 0px; border: 0px; font-family: Arial, Helvetica, sans-serif; font-size: 13px; font-stretch: inherit; line-height: 16.8999996185303px; vertical-align: baseline; color: rgb(128, 128, 128);">
<span style="font-size:14px;"><span style="font-family:trebuchet ms,helvetica,sans-serif;"><span style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline;"><span style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline;"><span style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; color: rgb(0, 0, 0);">The Tithe Barn was originally built in the 12th Century to store Tithes â€“ taxes paid to the Prioryâ€™s monks by the people living on the monastic estate. Following the dissolution of St Maryâ€™s Priory in 1542, the building was used for many different purposes, including a theatre in the 17th Century and a discotheque in the 20th Century.</span></span></span></span></span></p>
<p style="margin: 3px 0px 7px; padding: 0px; border: 0px; font-family: Arial, Helvetica, sans-serif; font-size: 13px; font-stretch: inherit; line-height: 16.8999996185303px; vertical-align: baseline; color: rgb(128, 128, 128);">
<span style="font-size:14px;"><span style="font-family:trebuchet ms,helvetica,sans-serif;"><span style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline;"><span style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline;"><span style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; color: rgb(0, 0, 0);">The Church took ownership of the Tithe Barn andÂ 
<strong style="margin: 0px; padding: 0px; border: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; color: rgb(96, 53, 18);"><a href="http://www.stmarys-priory.org/tithebarn/restoration.htm" style="margin: 0px; padding: 0px; border: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; color: rgb(96, 53, 18); text-decoration: none; cursor: pointer;">conservation</a>Â Â </strong>was undertaken in 2002 to stabilise the building allowing it to continue to be visited almost 900 years after it was first built.</span></span></span></span></span></p>
<p class="documentDescription" style="margin: 0em 0em 0.5em; line-height: 1.5em; font-weight: bold; color: rgb(85, 85, 85); font-family: 'Lucida Grande', Verdana, Lucida, 'Lucida sans', Helvetica, Arial, sans-serif; font-size: 13px;">Â </p>
<p style="margin: 3px 0px 7px; padding: 0px; border: 0px; font-family: Arial, Helvetica, sans-serif; font-size: 13px; font-stretch: inherit; line-height: 16.8999996185303px; vertical-align: baseline; color: rgb(128, 128, 128);">
<span style="font-size:14px;"><span style="font-family:trebuchet ms,helvetica,sans-serif;"><span style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline;"><span style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline;"><span style="margin: 0px; padding: 0px; border: 0px; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; color: rgb(0, 0, 0);">Today, visitors from all over the world come to learn about the fascinating and turbulent history of the Priory Church and to marvel at the magnificentÂ 
<a href="http://www.stmarys-priory.org/tithebarn/tapestry.htm" style="margin: 0px; padding: 0px; border: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-weight: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline; color: rgb(96, 53, 18); text-decoration: none; cursor: pointer;"><strong style="margin: 0px; padding: 0px; border: 0px; font-family: inherit; font-size: inherit; font-style: inherit; font-variant: inherit; font-stretch: inherit; line-height: inherit; vertical-align: baseline;">Abergavenny Tapestry</strong></a>Â which took a dedicated team of 60 ladies almost four years to complete.Â </span></span></span></span></span></p>
<div id="parent-fieldname-text" style="font-family: 'Lucida Grande', Verdana, Lucida, 'Lucida sans', Helvetica, Arial, sans-serif; font-size: 13px;">
<p style="color: rgb(68, 68, 68); margin: 0px 0px 0.75em; line-height: 1.5em;">
<br/>
<span style="font-size:14px;"><span style="font-family:trebuchet ms,helvetica,sans-serif;"><strong><span style="color:#008000;">How to get there:</span></strong><span style="color:#008000;">Â </span><strong style="margin: 0px; padding: 0px; border: 0px; font-family: arial, helvetica, sans-serif; font-stretch: inherit; line-height: 14.7719993591309px; vertical-align: baseline; color: rgb(0, 0, 0);">The Tourist Information Centre is located within the Tithe Barn,Â </strong><span style="color: rgb(0, 0, 0); line-height: 16.8999996185303px;">St Maryâ€™s Priory Church Vicarage, Monk Street, Abergavenny, NP7 5NDÂ </span></span></span></p>
<p style="color: rgb(68, 68, 68); margin: 0px 0px 0.75em; line-height: 1.5em;">Â </p>
<p style="margin: 0px 0px 0.75em; line-height: 1.5em;">
<span style="font-size: 14px;"><span style="font-family: 'trebuchet ms', helvetica, sans-serif;"><span style="color: rgb(0, 128, 0);"><strong>Nearest town or village:</strong></span><font color="#444444">Â </font><font color="#000000">Abergavenny.</font></span></span></p>
<p style="color: rgb(68, 68, 68); margin: 0px 0px 0.75em; line-height: 1.5em;">Â </p>
<p style="color: rgb(68, 68, 68); margin: 0px 0px 0.75em; line-height: 1.5em;">
<span style="font-size:14px;"><span style="font-family:trebuchet ms,helvetica,sans-serif;"><span style="color:#008000;"><strong>OS Grid Reference:Â </strong></span>Explorer Map OL 13 or Landranger Map 161 -Â SO 30037 14129</span></span></p>
<p style="color: rgb(68, 68, 68); margin: 0px 0px 0.75em; line-height: 1.5em;">Â </p>
<p style="color: rgb(68, 68, 68); margin: 0px 0px 0.75em; line-height: 1.5em;">
<span style="font-size:14px;"><span style="font-family:trebuchet ms,helvetica,sans-serif;"><span style="color:#008000;"><strong>Contact:</strong></span>Â Please telephoneÂ 
<span style="color: rgb(0, 0, 0); line-height: 14.7719993591309px;">01873 853254</span></span></span></p>
<p style="color: rgb(68, 68, 68); margin: 0px 0px 0.75em; line-height: 1.5em;">Â </p>
<p style="color: rgb(68, 68, 68); margin: 0px 0px 0.75em; line-height: 1.5em;">
<span style="font-size:14px;"><span style="font-family:trebuchet ms,helvetica,sans-serif;"><span style="color:#008000;"><strong>Facilities:Â </strong></span>Abergavenny is a busy market town with shops, restaurants, cafÃ©s, pubs and a covered market. Abergavenny Shopmobility hires out mobility scooters: 0800 298 3656.</span></span></p>
<p style="color: rgb(68, 68, 68); margin: 0px 0px 0.75em; line-height: 1.5em;">Â </p>
<p style="color: rgb(68, 68, 68); margin: 0px 0px 0.75em; line-height: 1.5em;">
<span style="font-size:14px;"><span style="font-family:trebuchet ms,helvetica,sans-serif;"><span style="color:#008000;"><strong>Parking:</strong></span>Â Car parking is right next to the information centre.</span></span></p>
<p style="color: rgb(68, 68, 68); margin: 0px 0px 0.75em; line-height: 1.5em;">Â </p>
<p style="color: rgb(68, 68, 68); margin: 0px 0px 0.75em; line-height: 1.5em;">
<span style="font-size:14px;"><span style="font-family:trebuchet ms,helvetica,sans-serif;"><span style="color:#008000;"><strong>Toilets:</strong>Â </span>Public toilets are located on the ground floor with level access from the Foodhall.Â </span></span></p></div>
<br/>

<!--SearchEnd//-->
<div class="hightlights"/></div></body></html>